import pytest
import pandas as pd
import numpy as np
from datetime import timedelta
from ml.anomaly_engine.stream_pipeline import StreamPipeline

def test_batch_vs_stream_consistency():
    import os
    import pytest
    if not os.path.exists('data/processed/hybrid_predictions_v2.csv'):
        pytest.skip('Batch predictions file not found')
    pipeline = StreamPipeline()
    
    # Load 500 rows
    N = 500
    df_raw = pd.read_csv('data/processed/aws_clean.csv', nrows=N)
    df_batch = pd.read_csv('data/processed/hybrid_predictions_v2.csv', nrows=N)
    
    results = []
    for i, row in df_raw.iterrows():
        res = pipeline.process_observation(
            timestamp=row['timestamp'],
            temperature=row['temperature'],
            pressure=row['pressure'],
            humidity=row['humidity']
        )
        results.append(res)
        
    # Compare after warmup (e.g. idx > 30)
    for i in range(31, N):
        b_score = df_batch.iloc[i]['final_anomaly_score']
        s_score = results[i]['anomaly_score']
        
        # Must match almost exactly
        assert np.isclose(b_score, s_score, atol=1e-5), f"Mismatch at idx {i}: batch={b_score}, stream={s_score}"
        
        b_flag = bool(df_batch.iloc[i]['anomaly_flag'])
        s_flag = bool(results[i]['anomaly_flag'])
        assert b_flag == s_flag, f"Flag mismatch at idx {i}"

def test_causality():
    # Process up to T
    p1 = StreamPipeline()
    df_raw = pd.read_csv('data/processed/aws_clean.csv', nrows=50)
    
    r1 = None
    for i in range(40):
        r1 = p1.process_observation(**df_raw.iloc[i].to_dict())
        
    # Process up to T+10
    p2 = StreamPipeline()
    r2 = None
    for i in range(50):
        res = p2.process_observation(**df_raw.iloc[i].to_dict())
        if i == 39:
            r2 = res
            
    # r1 must perfectly equal r2
    assert r1['anomaly_score'] == r2['anomaly_score']
    assert r1['sensor_health_temperature'] == r2['sensor_health_temperature']

def test_health_continuity_and_gaps():
    pipeline = StreamPipeline()
    ts = pd.Timestamp('2020-01-01 00:00:00')
    
    # Feed 40 normal rows to exit warmup
    for i in range(40):
        ts += pd.Timedelta(minutes=10)
        res = pipeline.process_observation(ts, 20.0, 1010.0, 50.0)
        
    assert res['processing_state'] == 'PROCESSED'
    assert res['temperature_status'] == 'HEALTHY'
    
    # Feed an anomaly
    ts += pd.Timedelta(minutes=10)
    res = pipeline.process_observation(ts, 40.0, 1010.0, 50.0)
    assert res['anomaly_flag'] is True
    assert res['sensor_health_temperature'] < 100.0
    
    # Time gap exactly > 30 mins
    ts += pd.Timedelta(minutes=31)
    res_gap = pipeline.process_observation(ts, 20.0, 1010.0, 50.0)
    
    # Verify gap penalty of -5 was applied (97 - 5 = 92)
    assert res_gap['sensor_health_temperature'] == 92.0

def test_warmup_behavior():
    pipeline = StreamPipeline()
    ts = pd.Timestamp('2020-01-01 00:00:00')
    
    res = pipeline.process_observation(ts, 20.0, 1010.0, 50.0)
    assert res['processing_state'] == 'WARMUP'
    # Health should NOT be degraded during warmup even if algorithms guess anomaly
    assert res['sensor_health_temperature'] == 100.0

def test_exact_89_features():
    pipeline = StreamPipeline()
    df_raw = pd.read_csv('data/processed/aws_clean.csv', nrows=100)
    df_features = pd.read_csv('data/processed/aws_synthetic_features.csv', nrows=100)
    
    mismatches = 0
    max_abs_diff = 0.0
    
    for i, row in df_raw.iterrows():
        pipeline.process_observation(
            timestamp=row['timestamp'],
            temperature=row['temperature'],
            pressure=row['pressure'],
            humidity=row['humidity']
        )
        
        if i == 50:
            stream_feat_dict = pipeline.feature_engineer.last_obs
            batch_feat_series = df_features.iloc[i]
            
            for col in pipeline.feature_cols:
                # Exclude evaluation labels not generated by feature engineer
                if col in ['is_anomaly', 'anomaly_type', 'affected_sensor', 'anomaly_id']:
                    continue
                    
                v_s = stream_feat_dict[col]
                v_b = batch_feat_series[col]
                
                if pd.isna(v_s) and pd.isna(v_b):
                    continue
                elif pd.isna(v_s) != pd.isna(v_b):
                    mismatches += 1
                elif isinstance(v_s, (int, float, np.number)) and isinstance(v_b, (int, float, np.number)):
                    diff = abs(v_s - v_b)
                    if diff > 1e-5:
                        mismatches += 1
                    max_abs_diff = max(max_abs_diff, diff)
            break
            
    assert mismatches == 0, f"Found {mismatches} mismatching features!"
    assert max_abs_diff < 1e-5, f"Max diff too high: {max_abs_diff}"
